# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MelbourneCafe' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MelbourneCafe
  pod 'Alamofire', '~> 4.4'
  
  # MD5 Method
  pod 'SwiftHash', git: 'https://github.com/onmyway133/SwiftHash'

end
